group: edge
dist: trusty

language: go

go:
  - 1.x
  - 1.6
  - 1.7.x
  - 1.8.x
  - master

install: true

before_install:
  # install docker-compose
  - sudo apt update
  - sudo apt install -y python-pip curl jq libxml2-utils
  - sudo pip install --upgrade httpie docker-compose
  - sudo usermod -aG docker $(whoami)
  # kill on ports
  - true | sudo kill $(sudo lsof -t -i:5432)

script:
  - export GOPATH="$GOPATH:$PWD"

  - export goApp=http-server-even-more-simpler
  - go install $goApp
  - ./bin/$goApp &
  - sleep 1
  - curl localhost:8080/files/
  - http :8080/files/
  - killall -9 $goApp

  - >
    for goApp in \
      http-serve-file \
      file-server\
    ; do
      go install $goApp
      ./bin/$goApp &
      sleep 1
      curl localhost:8080/files/index.html
      http :8080/files/index.html
      http :8080/files/favicon.ico
      killall -9 $goApp;
    done;

  - >
    for goApp in \
      handler-func \
      http-handler \
      webapp \
    ; do
      go install $goApp;
      ./bin/$goApp &
      sleep 1;
      curl localhost:8080;
      http :8080;
      killall -9 $goApp;
    done;
