group: edge
dist: trusty

language: go

go:
  - 1.x
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - master

install: true

before_install:
  - sudo apt update

  # install docker-compose
  - sudo apt install -y python-pip curl jq libxml2-utils
  - sudo pip install --upgrade httpie

  # daggerok bash functions
  - source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)

  # kill on ports
  - stop_any 5432 8080

script:
  - export GOPATH="${GOPATH}:${PWD}"

  - export goApp=http-server-even-more-simpler
  - go install $goApp
  - ./bin/$goApp &
  - wait_for 8080
  - curl localhost:8080/files/
  - http :8080/files/
  - stop_any 8080

  - >
    for goApp in \
      http-serve-file \
      file-server \
    ; do
      go install $goApp
      ./bin/$goApp &
      wait_for 8080
      curl localhost:8080/files/index.html
      http :8080/files/index.html
      http :8080/files/favicon.ico
      stop_any 8080
    done;

  - >
    for goApp in \
      handler-func \
      http-handler \
      webapp \
    ; do
      go install $goApp
      ./bin/$goApp &
      wait_for 8080
      curl localhost:8080
      http :8080
      stop_any 8080
    done
